# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PVQDGUt3t-3FI9Gef__JIcEahDXFvbZ
"""

!apt-get install pypy

import random
import timeit
def sum_random_numbers(n):
    return sum([random.random() for i in range(n)])
if __name__ == '__main__':
    n = 1000000
    print(sum_random_numbers(n))

n = 1000000
# Benchmark using Pypy
t2 = timeit.timeit(lambda: sum_random_numbers(n), number=10)
print("time", t2)